FROM rrdockerhub/ros-base-kinetic-arm32v7

LABEL authors = "Yu Okamoto <yu.okamoto@rapyuta-robotics.com>"

RUN apt-get update && apt-get install --no-install-recommends -y \
    ros-kinetic-usb-cam


